version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      target: runner
      dockerfile: ./apps/server/Dockerfile
      args:
        BUILD_MODE: local
    container_name: server
    restart: unless-stopped
    env_file:
      - .env
      - ./apps/server/.env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
    volumes:
      - /app/node_modules
      - /app/apps/server/node_modules
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  website:
    build:
      context: .
      target: runner
      dockerfile: ./apps/website/Dockerfile
      args:
        BUILD_MODE: local
        APP_PORT: 3001
        APP_HOSTNAME: omni.localhost
        NEXT_PUBLIC_APP_DOMAIN: omni.localhost:3001
        NEXT_PUBLIC_ADMIN_DOMAIN: admin.omni.localhost:3002
        NEXT_PUBLIC_SERVER_DOMAIN: server.omni.localhost:3000
    container_name: website
    restart: unless-stopped
    env_file:
      - .env
      - ./apps/website/.env.local
    environment:
      - NODE_ENV=production
      - APP_HTTP_URL=http://server:3000/trpc
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
    ports:
      - 3001:3001
    networks:
      - backend
    depends_on:
      - server

  admin:
    build:
      context: .
      target: runner
      dockerfile: ./apps/admin/Dockerfile
      args:
        BUILD_MODE: local
        APP_PORT: 3002
        APP_HOSTNAME: admin.omni.localhost
        NEXT_PUBLIC_APP_DOMAIN: admin.omni.localhost:3002
        NEXT_PUBLIC_WEBSITE_DOMAIN: omni.localhost:3001
        NEXT_PUBLIC_SERVER_DOMAIN: server.omni.localhost:3000
    container_name: admin
    restart: unless-stopped
    env_file:
      - .env
      - ./apps/admin/.env.local
    environment:
      - NODE_ENV=production
      - APP_HTTP_URL=http://server:3000/trpc
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
    ports:
      - 3002:3002
    networks:
      - backend
    depends_on:
      - server

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
